### Coordinates systems in 2d

* Cartesian

In [1]:
from analytic_geometry.coordinate_system.two_dimentional.cartesian import CartesianPoint_2d

In [2]:
a = CartesianPoint_2d(name="A", x=-1, y=15)
b = CartesianPoint_2d(name="B", x=1, y=-1)

In [3]:
a, b

(CartesianPoint_2d(name='A', x=-1.0, y=15.0),
 CartesianPoint_2d(name='B', x=1.0, y=-1.0))

In [4]:
a.to_array(), b.to_array()

(array([-1., 15.]), array([ 1., -1.]))

In [5]:
a.visualize()
b.visualize_in_cartesian()

Todo...
Todo...


In [6]:
a.euclidean_distanse_to(b), b.euclidean_distanse_to(a)

(np.float64(16.1245154965971), np.float64(16.1245154965971))

* Polar

In [7]:
import numpy as np

from analytic_geometry.coordinate_system.two_dimentional.polar import PolarPoint_2d

In [8]:
c = PolarPoint_2d(name="c", r=1, theta=np.pi / 3)
d = PolarPoint_2d(name="d", r=10, theta=np.pi / 4)

In [9]:
c

PolarPoint_2d(name='c', r=1.0, theta=1.0471975511965976)

In [10]:
d

PolarPoint_2d(name='d', r=10.0, theta=0.7853981633974483)

In [11]:
c.to_array(), d.to_array()

(array([1.        , 1.04719755]), array([10.        ,  0.78539816]))

In [12]:
c.to_cartesian(), d.to_cartesian()

(CartesianPoint_2d(name='c', x=0.5000000000000001, y=0.8660254037844386),
 CartesianPoint_2d(name='d', x=7.0710678118654755, y=7.071067811865475))

In [ ]:
c.visualize()
d.visualize_in_cartesian()

Todo...


In [15]:
c.euclidean_distanse_to(d), d.euclidean_distanse_to(c)

(np.float64(9.037780893240257), np.float64(9.037780893240257))

### Coordinates systems in 3d


* Cartesian

In [19]:
from analytic_geometry.coordinate_system.three_dimentional.cartesian import CartesianPoint_3d

In [20]:
A = CartesianPoint_3d(name="A", x=1, y=1, z=1)
B = CartesianPoint_3d(name="B", x=-1, y=0, z=-255)

In [23]:
A, B

(CartesianPoint_3d(name='A', x=1.0, y=1.0, z=1.0),
 CartesianPoint_3d(name='B', x=-1.0, y=0.0, z=-255.0))

In [24]:
A.to_array(), B.to_array()

(array([1., 1., 1.]), array([  -1.,    0., -255.]))

In [25]:
A.visualize()
B.visualize_in_cartesian()

Todo...
Todo...


In [27]:
A.euclidean_distanse_to(B), B.euclidean_distanse_to(A)

(np.float64(256.0097654387426), np.float64(256.0097654387426))

* Spherical


In [ ]:
...

* Cylindrical

In [ ]:
...